### ISSUE TITLE
大神的qq是多少，想做个brackets的插件

### ISSUE THREAD

**Issue by lilili87222** [yi-huan/brackets-theme-dark#1]
想做个brackets的插件我qq543246541

**Comment by yi-huan** [comment]
只是个民工，会做下主题，你想要做什么，直接在这说就行了。

**Comment by lilili87222** [comment]
添加文件管理功能，例如新建可以选择新建html，css文件

**Comment by yi-huan** [comment]
左侧不是已经有了文件管理，在空白处 右击就可以新建文件。 html, css 这些文件只要 你后缀写诗 html css 就可以了

**Comment by yi-huan** [comment]
如果你是嫌弃文件后缀看起来不明显，可以添加插件 [Brackets Icons ](https://github.com/ivogabe/Brackets-Icons) 或 [Tabs - Custom Working](https://github.com/DH3ALEJANDRO/custom-work-for-brackets) ， 我用 后者。后者比前面多了选项卡

**Comment by yi-huan** [comment]
再或者你是想要新建的 html 文件 有：
`<!DOCTYPE html>`
`<html lang="zh">`
`<head>`
`<meta charset="UTF-8">`
`<title>Document</title>`
`</head>`
`<body>`
`   `
`</body>`
`</html>`
就安装多个 [ emmet](http://emmet.io/) 插件。
里面很多快捷键。 
安装后 输入  !  再按 tab 键就会生成了。

**Comment by lilili87222** [comment]
大神，能加个qq聊么，功能可能在这个大神推荐的插件基础上还需要加点功能。如果大神有空可以把全部修改外包给大神。

**Comment by lilili87222** [comment]
我之前用eclipse，感觉用这个有些不习惯，想把里面一些功能调整下。愿意付费外包的。也可以合作当一个brackets的分支发布撒。

**Comment by yi-huan** [comment]
你说下什么功能？一般插件里面都有了。

**Comment by lilili87222** [comment]
喜欢这种交流和办事效率？

**Comment by yi-huan** [comment]
已发送！
